---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authentik-remote-cluster-authentik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: authentik-remote-cluster-authentik
subjects:
  - kind: ServiceAccount
    name: authentik-remote-cluster
    namespace: authentik