---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-redis
  namespace: authentik
spec:
  selector:
    matchLabels:
      app: authentik-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: authentik-redis
    spec:
      containers:
        - name: authentik-redis
          image: redis:6.0.9-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: authentik-redis
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 20
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 5
      volumes:
        - name: authentik-redis
          persistentVolumeClaim:
            claimName: authentik-redis

---
apiVersion: v1
kind: Service
metadata:
  name: authentik-redis
  namespace: authentik
spec:
  selector:
    app: authentik-redis
  ports:
    - name: redis
      port: 6379
      protocol: TCP
  type: ClusterIP