---
apiVersion: v1
kind: Service
metadata:
  name: authentik
  namespace: authentik
spec:
  ports:
      - name: http
        port: 9000
        targetPort: 9000
      - name: ldap
        port: 389
        targetPort: 389
  selector:
      app: authentik-server