---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-server
  namespace: authentik
  labels:
    app: authentik-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentik-server
  template:
    metadata:
      labels:
        app: authentik-server
    spec:
      containers:
        - name: authentik-server
          image: ghcr.io/goauthentik/server:2024.2.1
          imagePullPolicy: Always
          args: [ 'server' ]
          env:
            - name: AUTHENTIK_REDIS__HOST
              value: authentik-redis.authentik.svc.cluster.local
            - name: AUTHENTIK_POSTGRESQL__HOST
              valueFrom:
                secretKeyRef:
                  name: authentik-cluster-app
                  key: host
            - name: AUTHENTIK_POSTGRESQL__PORT
              valueFrom:
                  secretKeyRef:
                    name: authentik-cluster-app
                    key: port
            - name: AUTHENTIK_POSTGRESQL__USER
              valueFrom:
                secretKeyRef:
                  name: authentik-cluster-app
                  key: username
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-cluster-app
                  key: password
            - name: AUTHENTIK_POSTGRESQL__NAME
              valueFrom:
                secretKeyRef:
                  name: authentik-cluster-app
                  key: dbname
          volumeMounts:
            - mountPath: /media
              name: authentik-media
          envFrom:
            - secretRef:
                name: authentik-secrets
          ports:
            - containerPort: 9000
              name: http
          livenessProbe:
            httpGet:
              port: 9000
              path: /-/health/live/
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 9000
              path: /-/health/live/
            initialDelaySeconds: 40
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 5
      enableServiceLinks: true
      volumes:
        - name: authentik-media
          persistentVolumeClaim:
            claimName: authentik-media