apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: epicgames-pv-claim
  namespace: epicgames-redeem
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteMany
