---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-pool
  namespace: metallb-system
spec:
  addresses:
    {% for address in metallb_pool_addresses %}
    - {{ address }}
    {% endfor %}
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lb-pool-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - lb-pool
