---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.208/28
    - 2a01:cb10:047f:af00:83df:5930:ffff:0001/112

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lb-pool-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - lb-pool