apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ./manifests/ingress.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.12.2/manifests/install.yaml
namespace: argocd

patches:
  - path: patches/configmap-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
      namespace: argocd