apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pv-claim
  namespace: nextcloud
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 15Gi
  accessModes:
    - ReadWriteOnce
