- include_vars:
    file: dns-secrets.yaml

- name: Create apikey secrets
  kubernetes.core.k8s:
    state: present
    template:
      path: "secrets.yaml.j2"

- name: Apply traefik configmap
  kubernetes.core.k8s:
    state: present
    template:
      path: "configmap.yaml.j2"

- name: Add traefik to helm repos
  kubernetes.core.helm_repository:
    repo_name: traefik
    repo_url: https://helm.traefik.io/traefik
    state: present

- name: Install traefik from helm
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    namespace: kube-system
    create_namespace: yes
    update_repo_cache: yes
    state: present
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"

- name: Create ingress
  kubernetes.core.k8s:
    state: present
    template:
      path: "ingress.yaml.j2"
