---
- name: Install required packages
  apt:
    pkg:
      - nfs-common
      - open-iscsi
      - util-linux
    update_cache: yes
    state: present

- name: Add longhorn to helm repos
  kubernetes.core.helm_repository:
    repo_name: longhorn
    repo_url: https://charts.longhorn.io
    state: present

- name: Create storage folder
  file:
    path: /storage
    state: directory
    mode: 0755

- name: Install longhorn from helm
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    namespace: longhorn-system
    create_namespace: yes
    update_repo_cache: yes
    state: present
    values:
      defaultSettings:
        defaultDataPath: /storage
