---
- name: Add longhorn to helm repos
  kubernetes.core.helm_repository:
    repo_name: longhorn
    repo_url: https://charts.longhorn.io
    state: present

- name: Create storage folder
  file:
    path: /storage
    state: directory
    mode: 0755
  become: yes

- name: Install longhorn from helm
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    namespace: longhorn-system
    create_namespace: yes
    update_repo_cache: yes
    state: present
    values:
      defaultSettings:
        defaultDataPath: /storage

- name: Make longhorn the default storage class
  kubernetes.core.k8s:
    state: patched
    kind: StorageClass
    namespace: kube-system
    name: local-path
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
