---
- name: Add longhorn to helm repos
  kubernetes.core.helm_repository:
    repo_name: longhorn
    repo_url: https://charts.longhorn.io
    state: present

- name: If the storage folder exists, delete it
  file:
      path: "{{ item[1] }}"
      state: absent
  become: yes
  delegate_to: "{{ item[0] }}"
  run_once: true
  with_nested:
    - "{{ groups['storages'] }}"
    - ["/storage", "/var/lib/longhorn"]

- name: Create storage folder
  file:
    path: /storage
    state: directory
    mode: 0755
  become: yes
  loop: "{{ groups['storages'] }}"
  delegate_to: "{{ item }}"
  run_once: true

- name: Mark storage node as default disk
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Node
    name: "{{ hostvars[item]['vars']['node_name'] }}"
    definition:
      metadata:
        labels:
          node.longhorn.io/create-default-disk: "true"
  loop: "{{ query('inventory_hostnames', 'storages') }}"

- name: Install longhorn from helm
  kubernetes.core.helm:
    kubeconfig: /home/{{ ansible_ssh_user }}/.kube/config
    name: longhorn
    chart_ref: longhorn/longhorn
    namespace: longhorn-system
    create_namespace: yes
    update_repo_cache: yes
    state: present
    values:
      defaultSettings:
        defaultDataPath: /storage
  run_once: true
