---
- name: Upgrade packages
  apt:
    upgrade: true
    update_cache: true

- name: Install base packages
  apt:
    pkg:
      - vim
      - tmux
      - git
      - lsb-release
      - curl
      - wget
      - sudo
      - gnupg2
    state: present
