---
- name: Upgrade packages
  apt:
    upgrade: dist
    force_apt_get: yes

- name: Install base packages
  apt:
    pkg:
      - vim
      - tmux
      - git
      - neofetch
      - lsb-release
      - curl
      - wget
    state: present

- name: Reboot
  reboot:
