---
- name: Upgrade packages
  apt:
    upgrade: true
    update_cache: true

- name: Install base packages
  apt:
    pkg:
      - vim
      - tmux
      - git
      - lsb-release
      - curl
      - wget
      - sudo
      - gnupg2
    state: present

- name: Write tmux config
  copy:
      src: tmux.conf
      dest: /home/{{ ansible_user }}/.tmux.conf
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "u=rw,g=,o="