---
- name: Set same timezone on all nodes
  timezone:
    name: "{{ system_timezone }}"
  when: (system_timezone is defined)

- name: Set hostname
  hostname:
    name: "{{ hostvars[inventory_hostname]['vars']['node_name'] }}"
  when: (hostvars[inventory_hostname]['vars']['node_name'] is defined)

- name: Set boot behaviour (on raspberry)
  shell: raspi-config nonint do_boot_behaviour B1
  # only when the node is in the "raspberry" group
  when: ('raspberry' in group_names)

- name: Change Locale (Raspberry)
  shell: raspi-config nonint do_change_locale {{ system_locale | default('fr_FR.UTF-8') }}
  # only when the node is in the "raspberry" group
  when: ('raspberry' in group_names)

- name: Ensure the locale exists (Orange Pi)
  locale_gen:
    name: "{{ system_locale | default('fr_FR.UTF-8') }}"

    state: present
  # only when the node is in the "orange_pi" group
  when: ('orangepi' in group_names)

- name: Disable zram
  shell: systemctl disable zram-config
  # only when the node is in the "raspberry" group
  when: ('orangepi' in group_names)
  failed_when: false
- name: Remove tmpfs from /etc/fstab
  lineinfile:
      path: /etc/fstab
      state: absent
      regexp: 'tmpfs'
  # only when the node is in the "raspberry" group
  when: ('orangepi' in group_names)

# replace the ENABLED variable in /etc/default/armbian-zram-config
- name: Disable tmpfs in zram-config
  lineinfile:
      path: /etc/default/armbian-zram-config
      regexp: '^(.*)ENABLED=(.*)$'
      line: 'ENABLED=false'
  # only when the node is in the "raspberry" group
  when: ('orangepi' in group_names)

- name: Install required packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-apt
      - python3-launchpadlib
      - sudo
      - htop
    state: present