apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetector-pv-claim
  namespace: changedetector-io
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Mi
  accessModes:
    - ReadWriteMany
