---
- hosts: all
  gather_facts: true
  become: yes
  # since we're not sure if the command "sudo" is already installed, we use "su" instead
  become_flags: "-"
  become_method: su

  roles:
    # First, configure the system settings
    - role: system/system-config
      tags: [system]
    # Then, configure the network settings
    - role: system/network-config
      tags: [network]
    # Configure drivers
    - role: system/drivers
      tags: [drivers]
      when: ('orangepi' in group_names)
    # Configure base packages
    - role: system/base_packages
      tags: [base_packages]
    # Install fill shell
    - role: system/shell
      tags: [shell]
    #- role: system/users
    #  tags: [users]
