- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Install required packages for longhorn
      ansible.builtin.apt:
        pkg:
          - nfs-common
          - open-iscsi
          - util-linux
        update_cache: true
        state: present
    - name: Enable iscsid service
      ansible.builtin.service:
        name: iscsid
        enabled: true
        state: started
  tags:
    - storage

- hosts: masters
  gather_facts: true
  roles:
    - name: k3s-deployment/storage
      tags: storage
    - name: k3s-deployment/traefik
      tags: traefik
    - name: k3s-deployment/storage-ui
      tags: storage-ui
