---
- hosts: all
  gather_facts: yes
  become: yes

  vars:
    fish_as_default_shell: true

  roles:
    - system/system-config
    - system/dhcpcd
    - system/base_packages
    - system/fish_shell
