---
- name: Cleanup environment
  include_tasks: ./clean.yaml
  tags: [masters, kube-vip]

- name: Create manifests directory
  file:
    path: "{{ k3s_server_location }}/server/manifests"
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o="
  tags: [masters, kube-vip]

- name: Download kube-vip RBAC manifests
  get_url:
      url: https://kube-vip.io/manifests/rbac.yaml
      dest: "{{ k3s_server_location }}/server/manifests/kube-vip-rbac.yaml"
      owner: root
      group: root
      mode: "u=rwx,g=rx,o="
  tags: [masters, kube-vip]

- name: Generate kube-vip manifests
  template:
    src: kube-vip-manifests.yaml.j2
    dest: "{{ k3s_server_location }}/server/manifests/kube-vip.yaml"
    owner: root
    group: root
    mode: "u=rwx,g=rx,o="
  tags: [masters, kube-vip]
