apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: redis
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.30.82
  ports:
    - name: redis
      port: 6379
  selector:
    app: redis
