---
- name: Install UFW
  apt:
    name: ufw
    state: latest
  tags: [firewall]

- name: Ensure UFW is disabled
  ufw:
    state: disabled
  tags: [firewall]

- name: Clear all rules
  ufw:
    state: reset
  tags: [firewall]

- name: Allow OpenSSH coming from local network
  ufw:
    rule: allow
    name: SSH
    from_ip: "{{ item }}"
  tags: [firewall]
  with_items: "{{ firewall_allowed_local_ips }}"

- name: Allow HTTP(S)
  ufw:
    rule: allow
    name: WWW Full
  tags: [firewall]
  when: ("masters" in group_names)

- name: Allow k3s ports (2379-2380, 6443)
  ufw:
    rule: allow
    port: "{{ item[1] }}"
    proto: tcp
    comment: "k3s"
    from_ip: "{{ item[0] }}"
  tags: [firewall]
  with_nested:
    - "{{ firewall_allowed_local_ips }}"
    - [2379, 2380, 6443, 10250]

- name: Allow VPN
  ufw:
      rule: allow
      port: "1194"
      proto: udp
      comment: "VPN"
  tags: [firewall]
  when: ("masters" in group_names)

- name: Deny everything incoming
  ufw:
    policy: deny
    direction: incoming
  tags: [firewall]

- name: Allow everything outgoing
  ufw:
    policy: allow
    direction: outgoing
  tags: [firewall]

- name: Start UFW service
  service:
    name: ufw
    state: started
    enabled: yes
  tags: [firewall]

- name: Enable UFW
  ufw:
    state: enabled
  tags: [firewall]
