- name: Install python-kubernetes
  apt:
    name: python3-kubernetes
    state: present
  tags: [cluster, masters]

- name: Run everything as {{ ansible_ssh_user }}
  become: true
  become_user: "{{ ansible_ssh_user }}"
  tags: [cluster, masters]
  block:
    - name: Add node k8s label
      kubernetes.core.k8s:
        state: patched
        kind: Node
        name: "{{ hostvars[item]['vars']['node_name'] }}"
        definition:
          metadata:
            labels:
              device-type: "{{ hostvars[item]['node_type'] }}"
              device-version: "{{ ('node_version' in hostvars[item]['vars']) | ternary(hostvars[item]['vars']['node_version'], omit) }}"
              node-type: "{{ ('masters' in hostvars[item]['group_names']) | ternary('master', 'worker') }}"
      loop: "{{ query('inventory_hostnames', 'orangepi,raspberry') }}"
      tags: [cluster, masters, labels]

    - name: Add metallb to helm repos
      kubernetes.core.helm_repository:
        repo_name: metallb
        repo_url: https://metallb.github.io/metallb
        state: present
      tags: [cluster, masters, metallb]

    - name: Install metallb from helm
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        namespace: metallb-system
        create_namespace: yes
        update_repo_cache: yes
        state: present
      tags: [cluster, masters, metallb]

    - name: Apply MetalLB configuration
      kubernetes.core.k8s:
        state: present
        template:
          path: "values.yaml"
      tags: [cluster, masters, metallb]
