---
- name: Configure user
  user:
    name: "{{ ansible_user }}"
    groups: sudo
    append: yes
    shell: /usr/bin/fish

- name: Set authorized key taken from file
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', local_ssh_key) }}"
