---
apiVersion: v1
kind: Service
metadata:
  name: registry-svc
  namespace: registry
spec:
  ports:
    - name: http-r-ui
      port: 80
    - name: http-r-proxy
      port: 5000
  selector:
    app: registry
