---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pv-claim
  namespace: registry
spec:
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
