---
- name: Install Network Manager
  apt:
    name: network-manager
    state: present

- name: Configure static ip through NetworkManager
  nmcli:
    conn_name: eth0
    type: ethernet
    ip4: "{{ hostvars[inventory_hostname]['vars']['static_ip'] }}"
    gw4: "{{ hostvars[inventory_hostname]['vars']['static_gw'] }}"
    state: present
    autoconnect: yes

- name: Configure static ip v6 through NetworkManager
  nmcli:
      conn_name: eth0
      type: ethernet
      ip6: "{{ hostvars[inventory_hostname]['vars']['static_ip_v6'] }}"
      gw6: "{{ hostvars[inventory_hostname]['vars']['static_gw_v6'] }}"
      state: present
      autoconnect: yes
  when: hostvars[inventory_hostname]['vars']['static_ip_v6'] is defined and hostvars[inventory_hostname]['vars']['static_gw_v6'] is defined

- name: Enable Network Manager
  service:
    name: NetworkManager
    enabled: yes
    state: restarted
