---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aria2-pv
  namespace: aria2
  labels:
    type: "nfs"
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
  nfs:
    path: /srv/media
    server: 192.168.1.37

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aria2-pv-claim
  namespace: aria2
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
