---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aria2-dl-pv
  namespace: aria2
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  mountOptions:
    - hard
  local:
    path: /srv/aria2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - louis-rpi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aria2-dl-pv-claim
  namespace: aria2
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aria2-cfg-pv-claim
  namespace: aria2
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi
